= Building Tauri for CentOS/RHEL 7

== Problem

Tauri builds an AppImage that bundles all the necessary shared libraries except for glibc.
Tauri links against the glibc of the build environment.
For example, building on Ubuntu 22.10 links against glibc 2.35.

CentOS/RHEL provides glibc 2.17 (see https://distrowatch.com/table.php?distribution=redhat).

Attempting to run Regvue Desktop on CentOS/RHEL 7 that was built on Ubuntu 22.10 results in several "GLIBC_X.XX not found" errors (see <<error>>).

== Solution

Build on CentOS/RHEL 7 using Docker.

== Build the Docker Image

 git clone https://github.com/rfdonnelly/tauri-cross.git
 docker build -t tauri:centos7 tauri-cross/centos7

== Build the Tauri App

[source,sh]
----
cd $repo_root
----

[source,sh]
----
docker run -it --rm \
    -v $PWD:/src \
    -w /src \
    tauri:centos7 \
    /bin/bash -c "cd app && cargo tauri build"
----

=== Debugging AppImage Failure

[source,sh]
.Run on the Docker host
----
cd $repo_root
docker run -it --rm \
    -v $PWD:/src \
    -w /src \
    tauri:centos7 \
    /bin/bash
----

[source,sh]
.Run in Docker container
----
cd app
cargo tauri build # fails
----

==== Debugging AppImage Bundling Failure

[listing]
.Error message
----
    Bundling regvue_0.1.0_amd64.AppImage (/src/app/src-tauri/target/release/bundle/appimage/regvue_0.1.0_amd64.AppImage)
       Error failed to bundle project: error running appimage.sh: error running appimage.sh: `failed to run /src/app/src-tauri/target/release/bundle/appimage/build_appimage.sh`
----

[source,sh]
.Debug AppImage build failure
----
rm -rf src-tauri/target/release/bundle/appimage/regvue.AppDir
(cd src-tauri/target/release/bundle/appimage && ./build_appimage.sh) # fails
----

[listing]
.Error message
----
[gtk/stdout] Copying more libraries
[gtk/stderr] /root/.cache/tauri/linuxdeploy-plugin-gtk.sh: there is no 'libdir' variable for 'librsvg-2.0' library.
[gtk/stderr] Please check the 'librsvg-2.0.pc' file is present in $PKG_CONFIG_PATH (you may need to install the appropriate -dev/-devel package).
----

Add `yum install` of the `librsvg2-devel` package to the Dockerfile and try again.

[listing]
.Bundling is now successful!
----
> docker run -it --rm \
    -v $PWD:/src \
    -w /src \
    tauri:centos7 \
    /bin/bash -c "cd app && cargo tauri build"
...
    Bundling regvue_0.1.0_amd64.deb (/src/app/src-tauri/target/release/bundle/deb/regvue_0.1.0_amd64.deb)
    Bundling regvue_0.1.0_amd64.AppImage (/src/app/src-tauri/target/release/bundle/appimage/regvue_0.1.0_amd64.AppImage)    Finished 2 bundles at:
        /src/app/src-tauri/target/release/bundle/deb/regvue_0.1.0_amd64.deb
        /src/app/src-tauri/target/release/bundle/appimage/regvue_0.1.0_amd64.AppImage
----

==== Debugging Missing Shared Object

However, running the Tauri App results in a blank Tauri window and some error messages in the console.

I suspect the missing shared object and the blank window issues are unrelated.

[listing]
----
> app/src-tauri/target/release/bundle/appimage/regvue_0.1.0_amd64.AppImage
libgnutls.so.28: cannot open shared object file: No such file or directory
Failed to load module: /tmp/.mount_regvueh723d0/usr/lib64/gio/modules/libgiognutls.so

(regvue:3871): GLib-GIO-CRITICAL **: 13:48:04.328: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
libgnutls.so.28: cannot open shared object file: No such file or directory
Failed to load module: /tmp/.mount_regvueh723d0/usr/lib64/gio/modules/libgiognutls.so
libgnutls.so.28: cannot open shared object file: No such file or directory
Failed to load module: /tmp/.mount_regvueh723d0/usr/lib64/gio/modules/libgiognutls.so
----

The AppImage requires and bundles `usr/lib64/gio/modules/libgiognutls.so`.
This requires `libgnutls.so.28` which is not bundled.
This is found in `/lib64/` in CentOS 7 which the bundler seems not touch.
The bundler seems to only bundle things under `/usr/` and maybe treats everything under `/` as "system"?

I tried extracting the AppImage.

[source,sh]
----
app/src-tauri/target/release/bundle/appimage/regvue_0.1.0_amd64.AppImage --appimage-extract
mv squashfs-root .mount_regvue
----

Then manually copying `/lib64/libgnutls.so.28` out of the CentOS 7 Docker container into the extracted AppImage.

[source,sh]
----
mkdir .mount_regvue/lib64
cp /lib64/libgnutls.so.28 .mount_regvue/lib64
----

Then I tried running the extracted AppImage.

[source,sh]
----
env TMPDIR=$PWD $PWD/.mount_regvue/AppRun
----

And got different errors.

[listing]
----
libnettle.so.4: cannot open shared object file: No such file or directory
Failed to load module: /home/rfdonnelly/repos/registers/regvue/.mount_regvue/usr/lib64/gio/modules/libgiognutls.so
----

So I tried copying all of `/lib64/*` out of the container into the extracted AppImage (except for libc) and got yet more errors.

[listing]
----
regvue: /home/rfdonnelly/repos/registers/regvue/.mount_regvue/lib64/libuuid.so.1: version `UUID_2.31' not found (required by /lib/x86_64-linux-gnu/libfontconfig.so.1)
regvue: /home/rfdonnelly/repos/registers/regvue/.mount_regvue/lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /lib/x86_64-linux-gnu/libpng16.so.16)
----

So I tried removing these.
I got a different error.
I then removed the libraries the new error complained about an so on until all the errors were gone.
Here is the final list of additional libraries I had to manually add to the extracted AppImage from the CentOS 7 Docker container.

[listing]
---
lib64/libblkid.so.1
lib64/libffi.so.6
lib64/libgcc_s.so.1
lib64/libgio-2.0.so.0
lib64/libglib-2.0.so.0
lib64/libgmodule-2.0.so.0
lib64/libgmp.so.10
lib64/libgnutls.so.28
lib64/libgobject-2.0.so.0
lib64/libhogweed.so.2
lib64/libmount.so.1
lib64/libnettle.so.4
lib64/libp11-kit.so.0
lib64/libpcre.so.1
lib64/libresolv.so.2
lib64/libselinux.so.1
lib64/libtasn1.so.6
----

This could likely be further reduced by using an additive debug method where libraries are selectively added per error message.
Instead of subtractive debug where all are added then selectively removed per error message.

I can now run the extracted AppImage w/o errors.
However, the blank window issue persists.

==== Debugging the Blank Window

Try compiling in debug mode to enable the WebView dev console.

[source,sh]
----
docker run -it --rm \
    -v $PWD:/src \
    -w /src \
    tauri:centos7 \
    /bin/bash -c "cd app && cargo tauri build --debug"
----

[source,sh]
.Run the AppImage
----
app/src-tauri/target/debug/bundle/appimage/regvue_0.1.0_amd64.AppImage
----

[listing]
.stdout
----
libgnutls.so.28: cannot open shared object file: No such file or directory
Failed to load module: /tmp/.mount_regvueJYFe2E/usr/lib64/gio/modules/libgiognutls.so

(regvue:11647): GLib-GIO-CRITICAL **: 19:32:20.707: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
----

The missing `libgnutls.so.28` issue persists but I now have the "Inspect Element" option when I right click the WebView.

The Console tab in the dev tools shows the following error:

[listing]
----
SyntaxError: No identifiers allowed directly after numeric literal
----

I can't find the source location of the error.
But I suspect this is due to the use of BigInt literals like `1n` which is not likely supported by this old of a WebView.

== References

https://github.com/tauri-apps/tauri/issues/1355::
Provides a Dockerfile for building on CentOS7

[appendix]
[#error]
== Error Running Regvue Desktop on CentOS/RHEL 7

In this case, Regvue Desktop was built on Ubuntu 22.10 (glibc 2.35).

[source,sh]
----
./regvue_0.1.0_amd64.AppImage
----

[listing]
----
regvue: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by regvue)
regvue: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by regvue)
regvue: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by regvue)
regvue: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by regvue)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by regvue)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by regvue)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by regvue)
regvue: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by regvue)
regvue: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebkit2gtk-4.0.so.37)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgtk-3.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgtk-3.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgdk-3.so.0)
regvue: /lib64/libthai.so.0: version `LIBTHAI_0.1.25' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libpango-1.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libcairo.so.2)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libcairo.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgio-2.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgio-2.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgio-2.0.so.0)
regvue: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libgcc_s.so.1: version `GCC_7.0.0' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libjavascriptcoregtk-4.0.so.18)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libglib-2.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libglib-2.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libglib-2.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libglib-2.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libdbus-1.so.3)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libdbus-1.so.3)
regvue: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libcrypto.so.3)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libcrypto.so.3)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libcrypto.so.3)
regvue: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libicui18n.so.71)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libicui18n.so.71)
regvue: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libicuuc.so.71)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libicuuc.so.71)
regvue: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libicuuc.so.71)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libicuuc.so.71)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libicuuc.so.71)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libicuuc.so.71)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsystemd.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsystemd.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsystemd.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsystemd.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsystemd.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsystemd.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.30' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsystemd.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsystemd.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libxml2.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libxml2.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libxml2.so.2)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libxml2.so.2)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsqlite3.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsqlite3.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsqlite3.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libsqlite3.so.0)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libxslt.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libxslt.so.1)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/liblcms2.so.2)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwoff2dec.so.1.0.2)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwoff2dec.so.1.0.2)
regvue: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwoff2dec.so.1.0.2)
regvue: /lib64/libgpg-error.so.0: no version information available (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgcrypt.so.20)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgcrypt.so.20)
regvue: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgcrypt.so.20)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgstreamer-1.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgstreamer-1.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgstreamer-1.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgstpbutils-1.0.so.0)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgstaudio-1.0.so.0)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgsttag-1.0.so.0)regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgstvideo-1.0.so.0)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libpng16.so.16)
regvue: /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libpng16.so.16)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libopenjp2.so.7)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libopenjp2.so.7)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebp.so.7)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwebp.so.7)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libenchant-2.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgmodule-2.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwayland-server.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwayland-server.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwayland-server.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwayland-client.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libepoxy.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libxkbcommon.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwayland-cursor.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libwayland-cursor.so.0)
regvue: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libpixman-1.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libmount.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libmount.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libselinux.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.30' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libselinux.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libselinux.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libffi.so.8)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libcap.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/liblzma.so.5)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/liblzma.so.5)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libzstd.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libunwind.so.8)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libunwind.so.8)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libdw.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libdw.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgudev-1.0.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libpsl.so.5)
regvue: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgssapi_krb5.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgssapi_krb5.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libgssapi_krb5.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libevdev.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libXau.so.6)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libblkid.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libelf.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libudev.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libudev.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libudev.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libudev.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.30' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libudev.so.1)
regvue: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libunistring.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libunistring.so.2)
regvue: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libkrb5.so.3)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libkrb5.so.3)
regvue: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libkrb5.so.3)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libk5crypto.so.3)
regvue: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libk5crypto.so.3)
regvue: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libkrb5support.so.0)
regvue: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/rdonnell/.mount_/squashfs-root/usr/lib/libkrb5support.so.0)
----
